// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdMfs-pZdVfGMnbqoWarLwCl3BUWg5OjM',
    appId: '1:67027279981:web:54c9c4b2f47123b5aadf64',
    messagingSenderId: '67027279981',
    projectId: 'notiauto-94ee9',
    authDomain: 'notiauto-94ee9.firebaseapp.com',
    databaseURL: 'https://notiauto-94ee9-default-rtdb.firebaseio.com',
    storageBucket: 'notiauto-94ee9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACS1IHoNMIXj312Kvf0iVTmqhA6nwxARg',
    appId: '1:67027279981:android:73d498b864ea7428aadf64',
    messagingSenderId: '67027279981',
    projectId: 'notiauto-94ee9',
    databaseURL: 'https://notiauto-94ee9-default-rtdb.firebaseio.com',
    storageBucket: 'notiauto-94ee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpiAmHKWpMqY9L_26SeLdujTLF330PWxA',
    appId: '1:67027279981:ios:ab0bd2613980f823aadf64',
    messagingSenderId: '67027279981',
    projectId: 'notiauto-94ee9',
    databaseURL: 'https://notiauto-94ee9-default-rtdb.firebaseio.com',
    storageBucket: 'notiauto-94ee9.appspot.com',
    iosBundleId: 'com.example.notiautoSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpiAmHKWpMqY9L_26SeLdujTLF330PWxA',
    appId: '1:67027279981:ios:ab0bd2613980f823aadf64',
    messagingSenderId: '67027279981',
    projectId: 'notiauto-94ee9',
    databaseURL: 'https://notiauto-94ee9-default-rtdb.firebaseio.com',
    storageBucket: 'notiauto-94ee9.appspot.com',
    iosBundleId: 'com.example.notiautoSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdMfs-pZdVfGMnbqoWarLwCl3BUWg5OjM',
    appId: '1:67027279981:web:eb9fedf99c302b00aadf64',
    messagingSenderId: '67027279981',
    projectId: 'notiauto-94ee9',
    authDomain: 'notiauto-94ee9.firebaseapp.com',
    databaseURL: 'https://notiauto-94ee9-default-rtdb.firebaseio.com',
    storageBucket: 'notiauto-94ee9.appspot.com',
  );
}
